import { Category, Product, PromoCode, Review, Order } from './types';

export const CATEGORIES: Category[] = [
  {
    id: 'cat-1',
    name: 'Gâteaux d\'Anniversaire',
    slug: 'anniversaire',
    description: 'Des créations festives et spectaculaires pour souffler vos bougies avec gourmandise.',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    iconName: 'Cake',
  },
  {
    id: 'cat-2',
    name: 'Pièces Montées & Mariage',
    slug: 'mariage',
    description: 'L\'élégance absolue et le raffinement pour sublimer le plus beau jour de votre vie.',
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    iconName: 'HeartHandshake',
  },
  {
    id: 'cat-3',
    name: 'Cupcakes & Mignardises',
    slug: 'cupcakes',
    description: 'Petites bouchées de douceur aux parfums subtils et crèmes onctueuses.',
    imageUrl: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=800&q=80',
    iconName: 'Cookie',
  },
  {
    id: 'cat-4',
    name: 'Gâteaux Personnalisés',
    slug: 'personnalises',
    description: 'Votre imagination est notre seule limite. Thèmes, modelages 3D et lettrages dorés.',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    iconName: 'Sparkles',
  },
  {
    id: 'cat-5',
    name: 'Tartes & Entremets',
    slug: 'entremets',
    description: 'Pâtisserie fine française, miroirs brillants, mousses légères et fruits frais.',
    imageUrl: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?auto=format&fit=crop&w=800&q=80',
    iconName: 'Crown',
  },
  {
    id: 'cat-6',
    name: 'Coffrets Dégustation',
    slug: 'coffrets',
    description: 'Assortiments gourmands pour vos cadeaux, réunions d\'entreprise ou douceurs partagées.',
    imageUrl: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=800&q=80',
    iconName: 'Gift',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'cake-1',
    name: 'Le Royal Chocolat Grand Cru & Feuillantine',
    slug: 'royal-chocolat-grand-cru',
    tagline: 'Mousse chocolat Valrhona 70%, praliné croustillant et glaçage miroir noir',
    description: 'Notre création signature par excellence. Un biscuit moelleux au cacao intense, surmonté d\'un croustillant praliné noisette à la feuillantine dorée, et d\'une ganache montée au chocolat noir Grand Cru de Madagascar. Décoré de feuilles d\'or 24 carats comestibles.',
    price: 32000,
    discountPrice: 28000,
    category: 'anniversaire',
    categoryName: 'Gâteaux d\'Anniversaire',
    imageUrl: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 14,
    isFeatured: true,
    isPopular: true,
    isPromotion: true,
    rating: 4.95,
    reviewsCount: 142,
    portions: [6, 8, 12, 16],
    defaultPortions: 8,
    pricePerPortion: 3500,
    ingredients: ['Chocolat noir Valrhona 70%', 'Crème fraîche de Normandie', 'Praliné noisette du Piémont', 'Feuillantine', 'Œufs bio', 'Or pur 24k'],
    allergens: ['Lactose', 'Gluten', 'Fruits à coque', 'Œufs'],
    preparationTimeHours: 24,
  },
  {
    id: 'cake-2',
    name: 'Élégance Nuptiale Vanille Bourbon & Framboise',
    slug: 'elegance-nuptiale-vanille-framboise',
    tagline: 'Wedding cake moderne 3 étages, génoise vanillée et coulis de framboises fraîches',
    description: 'Une somptueuse pièce montée design habillée d\'une crème au beurre légère à la meringue suisse parfumée à la vanille Bourbon de Madagascar. Chaque étage alterne un sponge cake ultra aéré et un crémeux framboise acidulé récolté en verger artisanal.',
    price: 120000,
    discountPrice: 105000,
    category: 'mariage',
    categoryName: 'Pièces Montées & Mariage',
    imageUrl: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 5,
    isFeatured: true,
    isPopular: true,
    isPromotion: true,
    rating: 5.0,
    reviewsCount: 68,
    portions: [20, 35, 50, 80],
    defaultPortions: 35,
    pricePerPortion: 3000,
    ingredients: ['Gousses de Vanille Bourbon bio', 'Framboises fraîches', 'Beurre AOP Charentes-Poitou', 'Farine T45 Label Rouge', 'Fleurs comestibles'],
    allergens: ['Lactose', 'Gluten', 'Œufs'],
    preparationTimeHours: 48,
  },
  {
    id: 'cake-3',
    name: 'Red Velvet Velours & Cream Cheese Citronné',
    slug: 'red-velvet-velours',
    tagline: 'Biscuit rouge velouté au cacao fin, crème au mascarpone et zeste de citron vert',
    description: 'Le grand classique new-yorkais réinterprété avec la finesse de la pâtisserie française. Texture aérienne d\'un rouge profond et glaçage onctueux au cream cheese et zeste de yuzu pour un équilibre parfait entre douceur et fraîcheur.',
    price: 30000,
    category: 'anniversaire',
    categoryName: 'Gâteaux d\'Anniversaire',
    imageUrl: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 18,
    isFeatured: true,
    isPopular: false,
    isNew: true,
    rating: 4.88,
    reviewsCount: 94,
    portions: [6, 8, 10, 14],
    defaultPortions: 8,
    pricePerPortion: 3750,
    ingredients: ['Mascarpone italien', 'Cacao pur', 'Extrait de vanille bio', 'Citron vert', 'Beurre doux'],
    allergens: ['Lactose', 'Gluten', 'Œufs'],
    preparationTimeHours: 24,
  },
  {
    id: 'cake-4',
    name: 'Coffret 12 Cupcakes Haute Pâtisserie',
    slug: 'coffret-12-cupcakes-prestige',
    tagline: 'Assortiment de 12 cupcakes signatures : Pistache d\'Iran, Caramel Beurre Salé, Praliné & Ruby',
    description: 'Un festival de saveurs dans un écrin doré luxueux. 4 saveurs exclusives : Caramel fleur de sel de Guérande, Pistache d\'Iran et cœur coulant framboise, Ganache montée chocolat noir 66%, et Chocolat Ruby aux éclats de meringue.',
    price: 25000,
    discountPrice: 20000,
    category: 'cupcakes',
    categoryName: 'Cupcakes & Mignardises',
    imageUrl: 'https://images.unsplash.com/photo-1587668178277-295251f900ce?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 22,
    isFeatured: true,
    isPopular: true,
    isPromotion: true,
    rating: 4.92,
    reviewsCount: 110,
    portions: [12],
    defaultPortions: 12,
    pricePerPortion: 1660,
    ingredients: ['Pistache d\'Iran', 'Caramel artisanal à la fleur de sel', 'Chocolat noir Valrhona', 'Chocolat Ruby'],
    allergens: ['Lactose', 'Gluten', 'Fruits à coque', 'Œufs'],
    preparationTimeHours: 12,
  },
  {
    id: 'cake-5',
    name: 'Number Cake Floral & Fruits Rouges Exquis',
    slug: 'number-cake-floral-fruits-rouges',
    tagline: 'Pâte sablée amande, crème diplomate vanillée, macarons dorés et fruits rouges frais',
    description: 'Le gâteau le plus tendance pour célébrer un anniversaire inoubliable ! Choisissez vos chiffres ou lettres. Réalisé avec un sablé croustillant aux amandes, garni de voluptueux dômes de crème diplomate à la vanille, framboises, myrtilles fraîches et macarons faits main.',
    price: 45000,
    category: 'personnalises',
    categoryName: 'Gâteaux Personnalisés',
    imageUrl: 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1562440499-64c9a111f713?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 12,
    isFeatured: true,
    isPopular: true,
    isNew: false,
    rating: 4.97,
    reviewsCount: 175,
    portions: [10, 15, 20],
    defaultPortions: 10,
    pricePerPortion: 4500,
    ingredients: ['Poudre d\'amande brute', 'Vanille Bourbon', 'Framboises, myrtilles, mûres', 'Macarons artisanaux'],
    allergens: ['Fruits à coque', 'Lactose', 'Gluten', 'Œufs'],
    preparationTimeHours: 24,
  },
  {
    id: 'cake-6',
    name: 'Entremets Écrin Pistache de Sicile & Fleur d\'Oranger',
    slug: 'entremets-pistache-fleur-oranger',
    tagline: 'Mousse onctueuse à la pistache pure, biscuit financier et insert fraise gariguette',
    description: 'Une création haute couture d\'une grande délicatesse. L\'intensité boisée de la pistache de Sicile rencontre la fraîcheur florale de la fleur d\'oranger et l\'acidulé d\'une compotée de fraises gariguettes fondantes.',
    price: 35000,
    category: 'entremets',
    categoryName: 'Tartes & Entremets',
    imageUrl: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 9,
    isFeatured: true,
    isPopular: false,
    isNew: true,
    rating: 4.90,
    reviewsCount: 52,
    portions: [6, 8, 12],
    defaultPortions: 6,
    pricePerPortion: 5800,
    ingredients: ['Pâte de pistache pure 100%', 'Fraises Gariguettes', 'Eau de fleur d\'oranger bio', 'Chocolat blanc Ivoire'],
    allergens: ['Fruits à coque', 'Lactose', 'Gluten', 'Œufs'],
    preparationTimeHours: 36,
  },
  {
    id: 'cake-7',
    name: 'Drip Cake Or Noir & Macarons Caramel Salé',
    slug: 'drip-cake-or-noir-macarons',
    tagline: 'Coulures dorées au chocolat noir, génoise pralinée et macarons au beurre salé',
    description: 'Un chef-d\'œuvre visuel et gustatif conçu pour impressionner vos invités. Glaçage effet marbré noir et coulures dorées au chocolat, surmonté d\'une cascade de macarons croustillants et de perles croquantes.',
    price: 50000,
    discountPrice: 42000,
    category: 'personnalises',
    categoryName: 'Gâteaux Personnalisés',
    imageUrl: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?auto=format&fit=crop&w=800&q=80',
    additionalImages: [
      'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
    ],
    stock: 7,
    isFeatured: false,
    isPopular: true,
    isPromotion: true,
    rating: 4.94,
    reviewsCount: 88,
    portions: [10, 15, 20, 30],
    defaultPortions: 12,
    pricePerPortion: 3500,
    ingredients: ['Chocolat noir 70%', 'Caramel d\'Isigny', 'Macarons artisanaux', 'Poudre d\'or alimentaire'],
    allergens: ['Lactose', 'Gluten', 'Fruits à coque', 'Œufs'],
    preparationTimeHours: 24,
  },
  {
    id: 'cake-8',
    name: 'Le Caraïbes Passion, Mangue & Noix de Coco',
    slug: 'caraibes-passion-mangue-coco',
    tagline: 'Mousse exotique aux fruits de la passion, dacquoise coco et gelée de mangue fraîche',
    description: 'Une explosion ensoleillée en bouche. La légèreté de la noix de coco toastée associée au punch acidulé du fruit de la passion et à la douceur fondante de la mangue mûrie à point.',
    price: 32000,
    category: 'entremets',
    categoryName: 'Tartes & Entremets',
    imageUrl: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?auto=format&fit=crop&w=800&q=80',
    additionalImages: [],
    stock: 15,
    isFeatured: false,
    isPopular: false,
    isNew: false,
    rating: 4.82,
    reviewsCount: 46,
    portions: [6, 8, 10],
    defaultPortions: 8,
    pricePerPortion: 4000,
    ingredients: ['Purée de fruits de la passion', 'Mangues fraîches', 'Noix de coco râpée', 'Chocolat blanc'],
    allergens: ['Lactose', 'Œufs', 'Gluten'],
    preparationTimeHours: 24,
  },
  {
    id: 'cake-9',
    name: 'Coffret Prestige Macarons & Mignardises Étoilées',
    slug: 'coffret-prestige-macarons-mignardises',
    tagline: '24 pièces artisanales : 12 macarons d\'exception et 12 mini-tartelettes ganache',
    description: 'Le coffret ultime pour régaler vos convives ou offrir un présent inoubliable. Boîte noire mate aux dorures à chaud contenant nos 6 parfums médaillés de macarons et 6 mini-tartelettes au chocolat grand cru.',
    price: 35000,
    discountPrice: 30000,
    category: 'coffrets',
    categoryName: 'Coffrets Dégustation',
    imageUrl: 'https://images.unsplash.com/photo-1569864358642-9d1684040f43?auto=format&fit=crop&w=800&q=80',
    additionalImages: [],
    stock: 25,
    isFeatured: false,
    isPopular: true,
    isPromotion: true,
    rating: 4.96,
    reviewsCount: 130,
    portions: [24],
    defaultPortions: 24,
    pricePerPortion: 1250,
    ingredients: ['Amandes de Californie', 'Chocolat Guanaja 70%', 'Framboise', 'Pistache', 'Citron jaune'],
    allergens: ['Fruits à coque', 'Lactose', 'Gluten', 'Œufs'],
    preparationTimeHours: 12,
  },
];

export const PROMO_CODES: PromoCode[] = [
  {
    code: 'BIENVENUE20',
    discountPercent: 20,
    minAmount: 25000,
    description: '-20% sur toute votre première commande dès 25 000 FCFA',
    active: true,
  },
  {
    code: 'ANNIVERSAIRE15',
    discountPercent: 15,
    minAmount: 20000,
    description: '-15% spécial fête & anniversaire dès 20 000 FCFA',
    active: true,
  },
  {
    code: 'MARIAGE10',
    discountPercent: 10,
    minAmount: 70000,
    description: '-10% sur les pièces montées dès 70 000 FCFA',
    active: true,
  },
];

export const REVIEWS: Review[] = [
  {
    id: 'rev-1',
    authorName: 'Camille de Montmirail',
    rating: 5,
    comment: 'Le Royal Chocolat était tout simplement divin ! Le croustillant praliné et la finesse de la mousse ont conquis tous nos invités lors de l\'anniversaire de mon mari. Livraison impeccable à l\'heure exacte.',
    date: 'Il y a 3 jours',
    isVerifiedBuyer: true,
    productName: 'Le Royal Chocolat Grand Cru',
    occasion: 'Anniversaire 40 ans',
  },
  {
    id: 'rev-2',
    authorName: 'Alexandre & Sophie Martin',
    rating: 5,
    comment: 'Notre pièce montée de mariage était un chef-d\'œuvre. Aussi majestueuse visuellement qu\'exquise en bouche. Les convives nous en parlent encore ! Merci à toute l\'équipe pour leur écoute.',
    date: 'Il y a 1 semaine',
    isVerifiedBuyer: true,
    productName: 'Élégance Nuptiale Vanille Bourbon',
    occasion: 'Mariage au Domaine',
  },
  {
    id: 'rev-3',
    authorName: 'Élodie Laurent',
    rating: 5,
    comment: 'Number Cake sublime pour les 30 ans de ma sœur. Décoration florale fraîche splendide et crème diplomate légère comme un nuage. Commandé en 3 clics, service client d\'une grande gentillesse !',
    date: 'Il y a 2 semaines',
    isVerifiedBuyer: true,
    productName: 'Number Cake Floral & Fruits Rouges',
    occasion: 'Anniversaire 30 ans',
  },
  {
    id: 'rev-4',
    authorName: 'Julien B. - Agence Créative',
    rating: 5,
    comment: 'Les coffrets cupcakes pour notre événement d\'entreprise ont fait sensation. Finition ultra haut de gamme et saveurs raffinées. Nous recommandons les yeux fermés.',
    date: 'Il y a 3 semaines',
    isVerifiedBuyer: true,
    productName: 'Coffret 12 Cupcakes Haute Pâtisserie',
    occasion: 'Événement Corporate',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-1',
    orderNumber: 'CMD-8492',
    customerName: 'Sophie Bernard',
    customerEmail: 'sophie.bernard@example.com',
    customerPhone: '06 12 34 56 78',
    deliveryAddress: '14 Rue de la Paix',
    deliveryCity: 'Abidjan',
    deliveryPostalCode: '01 BP 458',
    deliveryDate: '2026-08-28',
    deliveryTimeSlot: '14h00 - 16h00',
    deliveryMethod: 'livraison_express',
    paymentMethod: 'carte',
    notes: 'Code porte 4812B, 3ème étage avec ascenseur.',
    items: [
      {
        productId: 'cake-1',
        productName: 'Le Royal Chocolat Grand Cru',
        productImage: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=800&q=80',
        quantity: 1,
        unitPrice: 28000,
        portions: 8,
        customMessage: 'Joyeux Anniversaire Thomas !',
      },
    ],
    subtotal: 28000,
    discountAmount: 5600,
    promoCode: 'BIENVENUE20',
    deliveryFee: 0,
    totalAmount: 22400,
    status: 'preparing',
    createdAt: '2026-08-26T09:15:00Z',
    updatedAt: '2026-08-26T10:00:00Z',
  },
  {
    id: 'ord-2',
    orderNumber: 'CMD-7319',
    customerName: 'Marc Dupont',
    customerEmail: 'marc.dupont@example.com',
    customerPhone: '07 98 76 54 32',
    deliveryAddress: '8 Boulevard de la République',
    deliveryCity: 'Dakar',
    deliveryPostalCode: 'BP 1204',
    deliveryDate: '2026-08-27',
    deliveryTimeSlot: '10h00 - 12h00',
    deliveryMethod: 'livraison_express',
    paymentMethod: 'carte',
    items: [
      {
        productId: 'cake-5',
        productName: 'Number Cake Floral & Fruits Rouges',
        productImage: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?auto=format&fit=crop&w=800&q=80',
        quantity: 1,
        unitPrice: 45000,
        portions: 10,
        customMessage: 'Chiffre 25',
      },
      {
        productId: 'cake-4',
        productName: 'Coffret 12 Cupcakes Haute Pâtisserie',
        productImage: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=800&q=80',
        quantity: 1,
        unitPrice: 20000,
        portions: 12,
      },
    ],
    subtotal: 65000,
    discountAmount: 0,
    deliveryFee: 0,
    totalAmount: 65000,
    status: 'in_delivery',
    createdAt: '2026-08-25T16:30:00Z',
    updatedAt: '2026-08-26T08:45:00Z',
  },
];
